dist: xenial
# sudo: false -> deprecated

language: node_js
node_js:
  - '10'

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  # - npm run test --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - npm run-script build
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/AngularMaterial
  on:
    branch: master